import type { Candidate } from '~/types';

export const DUMMY_CANDIDATES: Candidate[] = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@email.com',
    phone: '+1 (555) 123-4567',
    position: 'Software Engineer',
    department: 'Engineering',
    applicationDate: '2024-08-15',
    interviewStage: 'technical',
    status: 'scheduled',
    experience: 3,
    skills: ['JavaScript', 'React', 'Node.js', 'TypeScript'],
    interviewer: 'Sarah Johnson',
    interviewDate: '2024-09-02',
    interviewTime: '10:00 AM',
    resumeUrl: '/resumes/john-smith.pdf',
    linkedinUrl: 'https://linkedin.com/in/johnsmith'
  },
  {
    id: '2',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@email.com',
    phone: '+1 (555) 234-5678',
    position: 'UX Designer',
    department: 'Design',
    applicationDate: '2024-08-20',
    interviewStage: 'final',
    status: 'scheduled',
    experience: 5,
    skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping'],
    interviewer: 'Mike Chen',
    interviewDate: '2024-09-03',
    interviewTime: '2:00 PM',
    resumeUrl: '/resumes/emily-davis.pdf',
    linkedinUrl: 'https://linkedin.com/in/emilydavis'
  },
  {
    id: '3',
    firstName: 'Alex',
    lastName: 'Rodriguez',
    email: 'alex.rodriguez@email.com',
    phone: '+1 (555) 345-6789',
    position: 'Product Manager',
    department: 'Product',
    applicationDate: '2024-08-25',
    interviewStage: 'screening',
    status: 'active',
    experience: 7,
    skills: ['Product Strategy', 'Agile', 'Data Analysis', 'Roadmapping'],
    resumeUrl: '/resumes/alex-rodriguez.pdf'
  },
  {
    id: '4',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.garcia@email.com',
    phone: '+1 (555) 456-7890',
    position: 'Data Analyst',
    department: 'Analytics',
    applicationDate: '2024-08-28',
    interviewStage: 'technical',
    status: 'scheduled',
    experience: 2,
    skills: ['Python', 'SQL', 'Tableau', 'Statistics'],
    interviewer: 'David Brown',
    interviewDate: '2024-09-05',
    interviewTime: '3:30 PM',
    resumeUrl: '/resumes/maria-garcia.pdf'
  },
  {
    id: '5',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@email.com',
    phone: '+1 (555) 567-8901',
    position: 'DevOps Engineer',
    department: 'Engineering',
    applicationDate: '2024-08-10',
    interviewStage: 'offer',
    status: 'completed',
    experience: 6,
    skills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD'],
    interviewer: 'Sarah Johnson',
    interviewDate: '2024-08-28',
    interviewTime: '9:00 AM',
    resumeUrl: '/resumes/james-wilson.pdf',
    notes: 'Excellent technical skills, strong cultural fit'
  },
  {
    id: '6',
    firstName: 'Sarah',
    lastName: 'Kim',
    email: 'sarah.kim@email.com',
    phone: '+1 (555) 678-9012',
    position: 'Frontend Developer',
    department: 'Engineering',
    applicationDate: '2024-09-01',
    interviewStage: 'applied',
    status: 'active',
    experience: 4,
    skills: ['Vue.js', 'React', 'CSS', 'JavaScript'],
    resumeUrl: '/resumes/sarah-kim.pdf'
  },
  {
    id: '7',
    firstName: 'Michael',
    lastName: 'Thompson',
    email: 'michael.thompson@email.com',
    phone: '+1 (555) 789-0123',
    position: 'Marketing Manager',
    department: 'Marketing',
    applicationDate: '2024-08-18',
    interviewStage: 'final',
    status: 'active',
    experience: 8,
    skills: ['Digital Marketing', 'SEO', 'Content Strategy', 'Analytics'],
    resumeUrl: '/resumes/michael-thompson.pdf',
    linkedinUrl: 'https://linkedin.com/in/michaelthompson'
  },
  {
    id: '8',
    firstName: 'Jessica',
    lastName: 'Brown',
    email: 'jessica.brown@email.com',
    phone: '+1 (555) 890-1234',
    position: 'HR Specialist',
    department: 'Human Resources',
    applicationDate: '2024-08-22',
    interviewStage: 'screening',
    status: 'active',
    experience: 3,
    skills: ['Recruitment', 'Employee Relations', 'HRIS', 'Compliance'],
    resumeUrl: '/resumes/jessica-brown.pdf'
  },
  {
    id: '9',
    firstName: 'David',
    lastName: 'Lee',
    email: 'david.lee@email.com',
    phone: '+1 (555) 901-2345',
    position: 'Backend Developer',
    department: 'Engineering',
    applicationDate: '2024-08-12',
    interviewStage: 'hired',
    status: 'hired',
    experience: 5,
    skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Microservices'],
    interviewer: 'Sarah Johnson',
    interviewDate: '2024-08-30',
    interviewTime: '11:00 AM',
    resumeUrl: '/resumes/david-lee.pdf',
    notes: 'Strong technical background, excellent communication'
  },
  {
    id: '10',
    firstName: 'Lisa',
    lastName: 'Wang',
    email: 'lisa.wang@email.com',
    phone: '+1 (555) 012-3456',
    position: 'QA Engineer',
    department: 'Engineering',
    applicationDate: '2024-08-05',
    interviewStage: 'rejected',
    status: 'rejected',
    experience: 2,
    skills: ['Manual Testing', 'Automation', 'Selenium', 'TestNG'],
    interviewer: 'Mike Chen',
    interviewDate: '2024-08-25',
    interviewTime: '1:00 PM',
    resumeUrl: '/resumes/lisa-wang.pdf',
    notes: 'Good skills but not the right fit for current role'
  }
];