import type { LeaveType, ApprovalWorkflow, AccrualMethod, EmployeeEligibility } from '~/types';

// Leave Types Dummy Data
export const LEAVE_TYPES_DATA: LeaveType[] = [
  {
    id: 'LT001',
    name: 'Annual Leave',
    code: 'AL',
    description: 'Paid time off for vacation and personal time',
    icon: 'i-material-symbols:calendar-month',
    color: '#10b981',
    status: 'active',
    requiresApproval: true,
    approvalWorkflow: 'manager-hr',
    requiresDocumentation: false,
    maxConsecutiveDays: 14,
    minNoticePeriod: 7,
    allowHalfDays: true,
    applicableGender: 'all',
    isPaid: true,
    accrualMethod: 'annual-fixed',
    annualDays: 15,
    maxBalanceLimit: 30,
    allowCarryOver: true,
    maxCarryOverDays: 5,
    carryOverExpiryMonths: 3,
    prorationEnabled: true,
    negativeBalanceAllowed: false,
    eligibility: ['probation', 'permanent', 'contract'],
    minTenureMonths: 0,
    blackoutDates: [],
    usageCount: 145,
    approvalRate: 98,
    createdBy: 'HR Admin',
    createdAt: '2024-01-15',
    modifiedBy: 'HR Admin',
    modifiedAt: '2024-06-20'
  },
  {
    id: 'LT002',
    name: 'Sick Leave',
    code: 'SL',
    description: 'Leave for medical reasons and health-related issues',
    icon: 'i-material-symbols:emergency',
    color: '#f59e0b',
    status: 'active',
    requiresApproval: false,
    approvalWorkflow: null,
    requiresDocumentation: true,
    requiredDocuments: 'Medical certificate for absences over 2 days',
    maxConsecutiveDays: 10,
    minNoticePeriod: 0,
    allowHalfDays: true,
    applicableGender: 'all',
    isPaid: true,
    accrualMethod: 'annual-fixed',
    annualDays: 12,
    maxBalanceLimit: 24,
    allowCarryOver: true,
    maxCarryOverDays: 12,
    carryOverExpiryMonths: 12,
    prorationEnabled: true,
    negativeBalanceAllowed: true,
    maxNegativeBalance: 3,
    eligibility: ['permanent', 'contract'],
    minTenureMonths: 0,
    blackoutDates: [],
    usageCount: 89,
    approvalRate: 100,
    createdBy: 'HR Admin',
    createdAt: '2024-01-15',
    modifiedBy: 'HR Manager',
    modifiedAt: '2024-03-10'
  },
  {
    id: 'LT003',
    name: 'Personal Leave',
    code: 'PL',
    description: 'Leave for personal matters and emergencies',
    icon: 'i-material-symbols:person',
    color: '#3b82f6',
    status: 'active',
    requiresApproval: true,
    approvalWorkflow: 'manager',
    requiresDocumentation: false,
    maxConsecutiveDays: 3,
    minNoticePeriod: 3,
    allowHalfDays: true,
    applicableGender: 'all',
    isPaid: true,
    accrualMethod: 'annual-fixed',
    annualDays: 5,
    maxBalanceLimit: 5,
    allowCarryOver: false,
    prorationEnabled: true,
    negativeBalanceAllowed: false,
    eligibility: ['permanent'],
    minTenureMonths: 6,
    blackoutDates: [],
    usageCount: 67,
    approvalRate: 95,
    createdBy: 'HR Admin',
    createdAt: '2024-01-15',
    modifiedBy: 'HR Admin',
    modifiedAt: '2024-01-15'
  },
  {
    id: 'LT004',
    name: 'Maternity Leave',
    code: 'ML',
    description: 'Leave for pregnancy, childbirth, and postpartum care',
    icon: 'i-material-symbols:family-restroom',
    color: '#ec4899',
    status: 'active',
    requiresApproval: true,
    approvalWorkflow: 'hr',
    requiresDocumentation: true,
    requiredDocuments: 'Medical certificate confirming pregnancy',
    maxConsecutiveDays: 120,
    minNoticePeriod: 30,
    allowHalfDays: false,
    applicableGender: 'female',
    isPaid: true,
    accrualMethod: 'no-accrual',
    maxBalanceLimit: 0,
    allowCarryOver: false,
    prorationEnabled: false,
    negativeBalanceAllowed: false,
    eligibility: ['permanent'],
    minTenureMonths: 12,
    blackoutDates: [],
    usageCount: 8,
    approvalRate: 100,
    createdBy: 'HR Admin',
    createdAt: '2024-01-15',
    modifiedBy: 'HR Admin',
    modifiedAt: '2024-01-15'
  },
  {
    id: 'LT005',
    name: 'Paternity Leave',
    code: 'PTL',
    description: 'Leave for fathers following the birth or adoption of a child',
    icon: 'i-material-symbols:family-restroom',
    color: '#8b5cf6',
    status: 'active',
    requiresApproval: true,
    approvalWorkflow: 'hr',
    requiresDocumentation: true,
    requiredDocuments: 'Birth certificate or adoption papers',
    maxConsecutiveDays: 14,
    minNoticePeriod: 14,
    allowHalfDays: false,
    applicableGender: 'male',
    isPaid: true,
    accrualMethod: 'no-accrual',
    maxBalanceLimit: 0,
    allowCarryOver: false,
    prorationEnabled: false,
    negativeBalanceAllowed: false,
    eligibility: ['permanent'],
    minTenureMonths: 12,
    blackoutDates: [],
    usageCount: 12,
    approvalRate: 100,
    createdBy: 'HR Admin',
    createdAt: '2024-01-15',
    modifiedBy: 'HR Admin',
    modifiedAt: '2024-01-15'
  },
  {
    id: 'LT006',
    name: 'Unpaid Leave',
    code: 'UL',
    description: 'Leave without pay for extended personal reasons',
    icon: 'i-material-symbols:block',
    color: '#6b7280',
    status: 'active',
    requiresApproval: true,
    approvalWorkflow: 'manager-hr',
    requiresDocumentation: false,
    maxConsecutiveDays: 30,
    minNoticePeriod: 14,
    allowHalfDays: false,
    applicableGender: 'all',
    isPaid: false,
    accrualMethod: 'no-accrual',
    maxBalanceLimit: 0,
    allowCarryOver: false,
    prorationEnabled: false,
    negativeBalanceAllowed: false,
    eligibility: ['permanent'],
    minTenureMonths: 12,
    blackoutDates: [
      { startDate: `${new Date().getFullYear()}-12-20`, endDate: `${new Date().getFullYear()}-12-31`, reason: 'Year-end freeze' }
    ],
    usageCount: 5,
    approvalRate: 80,
    createdBy: 'HR Admin',
    createdAt: '2024-01-15',
    modifiedBy: 'HR Manager',
    modifiedAt: '2024-09-05'
  },
  {
    id: 'LT007',
    name: 'Bereavement Leave',
    code: 'BL',
    description: 'Leave for death of immediate family member',
    icon: 'i-material-symbols:heart-check',
    color: '#000000',
    status: 'active',
    requiresApproval: false,
    approvalWorkflow: null,
    requiresDocumentation: true,
    requiredDocuments: 'Death certificate or funeral notice',
    maxConsecutiveDays: 5,
    minNoticePeriod: 0,
    allowHalfDays: false,
    applicableGender: 'all',
    isPaid: true,
    accrualMethod: 'no-accrual',
    maxBalanceLimit: 0,
    allowCarryOver: false,
    prorationEnabled: false,
    negativeBalanceAllowed: false,
    eligibility: ['probation', 'permanent', 'contract'],
    minTenureMonths: 0,
    blackoutDates: [],
    usageCount: 3,
    approvalRate: 100,
    createdBy: 'HR Admin',
    createdAt: '2024-02-10',
    modifiedBy: 'HR Admin',
    modifiedAt: '2024-02-10'
  },
  {
    id: 'LT008',
    name: 'Study Leave',
    code: 'STL',
    description: 'Leave for educational or professional development purposes',
    icon: 'i-material-symbols:school',
    color: '#0ea5e9',
    status: 'inactive',
    requiresApproval: true,
    approvalWorkflow: 'manager-hr',
    requiresDocumentation: true,
    requiredDocuments: 'Enrollment confirmation or exam schedule',
    maxConsecutiveDays: 5,
    minNoticePeriod: 14,
    allowHalfDays: true,
    applicableGender: 'all',
    isPaid: false,
    accrualMethod: 'annual-fixed',
    annualDays: 5,
    maxBalanceLimit: 10,
    allowCarryOver: true,
    maxCarryOverDays: 5,
    carryOverExpiryMonths: 12,
    prorationEnabled: false,
    negativeBalanceAllowed: false,
    eligibility: ['permanent'],
    minTenureMonths: 24,
    blackoutDates: [
      { startDate: `${new Date().getFullYear()}-12-01`, endDate: `${new Date().getFullYear()}-12-31`, reason: 'Peak season' }
    ],
    usageCount: 0,
    approvalRate: 0,
    createdBy: 'HR Manager',
    createdAt: '2024-07-01',
    modifiedBy: 'HR Manager',
    modifiedAt: '2024-10-15'
  }
];

// Approval Workflow Options
export const APPROVAL_WORKFLOW_OPTIONS: { value: ApprovalWorkflow | null; label: string }[] = [
  { value: 'manager', label: 'Manager Only' },
  { value: 'hr', label: 'HR Only' },
  { value: 'manager-hr', label: 'Manager → HR' },
  { value: null, label: 'No Approval Required' }
];

// Accrual Method Options
export const ACCRUAL_METHOD_OPTIONS: { value: AccrualMethod; label: string }[] = [
  { value: 'annual-fixed', label: 'Annual Fixed' },
  { value: 'monthly-accrual', label: 'Monthly Accrual' },
  { value: 'no-accrual', label: 'No Accrual (Unlimited/One-time)' },
  { value: 'custom', label: 'Custom' }
];

// Icon Options
export const ICON_OPTIONS = [
  { value: 'i-material-symbols:calendar-month', label: 'Calendar' },
  { value: 'i-material-symbols:emergency', label: 'Medical (Heart Pulse)' },
  { value: 'i-material-symbols:person', label: 'User' },
  { value: 'i-material-symbols:family-restroom', label: 'Family' },
  { value: 'i-material-symbols:block', label: 'Block (Circle Slash)' },
  { value: 'i-material-symbols:heart-check', label: 'Heart' },
  { value: 'i-material-symbols:school', label: 'Graduation Cap' },
  { value: 'i-material-symbols:flight', label: 'Plane' },
  { value: 'i-material-symbols:home', label: 'Home' },
  { value: 'i-material-symbols:work', label: 'Briefcase' }
];

// Color Palette Options
export const COLOR_PALETTE_OPTIONS = [
  { value: '#10b981', label: 'Green' },
  { value: '#f59e0b', label: 'Orange' },
  { value: '#3b82f6', label: 'Blue' },
  { value: '#ec4899', label: 'Pink' },
  { value: '#8b5cf6', label: 'Purple' },
  { value: '#6b7280', label: 'Gray' },
  { value: '#ef4444', label: 'Red' },
  { value: '#0ea5e9', label: 'Sky Blue' },
  { value: '#000000', label: 'Black' },
  { value: '#14b8a6', label: 'Teal' }
];

// Employee Eligibility Options
export const EMPLOYEE_ELIGIBILITY_OPTIONS: { value: EmployeeEligibility; label: string }[] = [
  { value: 'probation', label: 'Probation Employees' },
  { value: 'permanent', label: 'Permanent Employees' },
  { value: 'contract', label: 'Contract Employees' }
];

// Default Leave Types Templates for Quick Setup
export const DEFAULT_LEAVE_TYPES_TEMPLATE = [
  {
    name: 'Annual Leave',
    code: 'AL',
    description: 'Paid time off for vacation and personal time',
    icon: 'i-material-symbols:calendar-month',
    color: '#10b981',
    requiresApproval: true,
    isPaid: true,
    accrualMethod: 'annual-fixed' as AccrualMethod,
    annualDays: 15,
    status: 'active' as const,
    applicableGender: 'all' as const,
    eligibility: ['probation', 'permanent', 'contract'] as EmployeeEligibility[]
  },
  {
    name: 'Sick Leave',
    code: 'SL',
    description: 'Leave for medical reasons and health-related issues',
    icon: 'i-material-symbols:emergency',
    color: '#f59e0b',
    requiresApproval: false,
    isPaid: true,
    accrualMethod: 'annual-fixed' as AccrualMethod,
    annualDays: 12,
    status: 'active' as const,
    applicableGender: 'all' as const,
    eligibility: ['permanent', 'contract'] as EmployeeEligibility[]
  },
  {
    name: 'Personal Leave',
    code: 'PL',
    description: 'Leave for personal matters and emergencies',
    icon: 'i-material-symbols:person',
    color: '#3b82f6',
    requiresApproval: true,
    isPaid: true,
    accrualMethod: 'annual-fixed' as AccrualMethod,
    annualDays: 5,
    status: 'active' as const,
    applicableGender: 'all' as const,
    eligibility: ['permanent'] as EmployeeEligibility[]
  }
];

// Applicable Gender Options
export const APPLICABLE_GENDER_OPTIONS = [
  { value: 'all', label: 'All Employees' },
  { value: 'male', label: 'Male Only' },
  { value: 'female', label: 'Female Only' }
];
